<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:GridView ID="gvAmmu" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="gvAmmu_RowCancelingEdit" OnRowEditing="gvAmmu_RowEditing" OnRowUpdating="gvAmmu_RowUpdating">
        <Columns>
            <asp:TemplateField HeaderText="Aid">
                <ItemTemplate><asp:Label ID="lblAid" runat="server" Text='<%#Eval("Aid") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Name">
                <ItemTemplate><asp:Label ID="lblName" runat="server" Text='<%#Eval("Name") %>'></asp:Label></ItemTemplate>
                <EditItemTemplate><asp:TextBox ID="tbName" runat="server" Text='<%#Eval("Name") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Age">
                <ItemTemplate><asp:Label ID="lblAge" runat="server" Text='<%#Eval("Age") %>'></asp:Label></ItemTemplate>
                <EditItemTemplate><asp:TextBox ID="tbAge" runat="server" Text='<%#Eval("Age") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>
        </Columns>

    </asp:GridView>
    </div>
    </form>
</body>
</html>
